### ISSUE TITLE
How do I compile it?

### ISSUE THREAD

**Issue by dderoit** [Louisvh/NDS-controller-android-host#1]
How do I compile it? The Google Play Store link doesn't go anymore.

**Comment by Nomagno** [comment]
Hello! I'm afraid I have not managed to compile it either. I have however forked the main repo and you can find the same binary that used to be in the Play Store over there along with a bunch of new servers ;) . I'm planning on rewriting it anyways so keep an eye out!
https://github.com/Nomagno/NDS-NetworkedInput

**Comment by Louisvh** [comment]
Sorry about the radio silence, y'all. The project was all sorts of broken on modern Android versions and back then I didn't have time to patch it up. Recently someone asked me about it again and I figured I'd spend a couple of hours to get it running again. You've probably long since forgotten this exists, but in case you see the notification and want to give it a try: the current version _should_ compile without a hitch. I've also added a pre-compiled apk if you just want to play with it for a bit.

That said, I'm mostly running off of Android knowledge from 2011 and haphazardly Googled snippets on how to replace all of the deprecated functions. It works on my machine though, so there's a decent chance it'll work for you, too.
